services:
  app:
    image: nosqlproject
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
        - ./:/app
        - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd
      volumes: /data/db
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongo", "--username", "root", "--password", "pwd", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pwd

volumes:
  mongo_data:
